### ISSUE TITLE
How does Variable Inline work?

### ISSUE THREAD

**Issue by shivapoudel** [tianyiw2013/vscode-php-docblocker#12]
How can I generate an inline variable? Demo will be better!

**Comment by shivapoudel** [comment]
Also, what is the use of  and where is it effective "php-docblocker2.variableTemplate"

**Comment by tianyiw2013** [comment]
```php
/** @var mixed $user  */
$user = getUser();

/**
 * user
 *
 * @var mixed $user
 */
$user = getUser();
```

![vscode](https://user-images.githubusercontent.com/4644588/125017418-afe24780-e0a5-11eb-8df6-fd398915909c.gif)

**Comment by shivapoudel** [comment]
@tianyiw2013 I have following setting so this is not working for me:

```
	"php-docblocker2.extra": [
		"@since ${###:1.0.0}",
	],
```

**Comment by shivapoudel** [comment]
@tianyiw2013 After updating the extension and adding this also, I couldn't get the expected result because since tag is added
```json
	"php-docblocker2.extra": [
		{
			"content": "@since ${###:1.0.0}",
			"after": "message",
			"gapAfter": true,
		},
	],
```

Expected:
![image](https://user-images.githubusercontent.com/3774827/125034918-e8d3e980-e0b0-11eb-9cbd-2446e3709412.png)

Got:
![image](https://user-images.githubusercontent.com/3774827/125034981-fb4e2300-e0b0-11eb-8708-a4ded6900eda.png)

Please check once if this is replicable on your end :)

**Comment by tianyiw2013** [comment]
New version 2.1.10 released.

```json

    "php-docblocker2.extra": [
        {
            "content": "@since ${###:1.0.0}",
            "after": "message",
            "gapAfter": true,
            "scope": "class,func",
        },
        {
            "content": "@since ${###:1.0.0}",
            "after": "message",
            "scope": "prop",
        },
    ],
    "php-docblocker2.defaultParameterDescription": true,
```

```php
/**
 * testaa
 *
 * @since 1.0.0
 */
class testaa
{
    /**
     * prop
     *
     * @since 1.0.0
     * @var mixed
     */
    protected $prop;

    /**
     * construct
     *
     * @since 1.0.0
     *
     * @param mixed $a a
     */
    function __construct($a)
    {

        /** @var int $xx  */
        $xx = 1;
    }
}
```

**Comment by shivapoudel** [comment]
Thank you this resolved the issue.

My suggestion: Please do rename the VSCode extension to "PHP DocBlocker 2" and slug in the marketplace like `tianyiw.php-docblocker-2` with some space in name and hyphen in a slug. Just for an example like of Bracket Pair colorizer in the screenshot below. This looks more pretty and many developers will gonna find it out because of the search index! 
![image](https://user-images.githubusercontent.com/3774827/125064682-9c000b00-e0d0-11eb-9276-fb83a6b5c347.png)

谢谢，我的朋友！

**Comment by tianyiw2013** [comment]
ok, thank you
