### ISSUE TITLE

Support @since tag @param short description

### ISSUE THREAD

**Issue by shivapoudel** [tianyiw2013/vscode-php-docblocker#9]
Please do support `@since` tag before `@param` one before with gap support and also allow `@param` short description as necessary for code sniffer and this will save time if we do during docblock creation.

**Comment by tianyiw2013** [comment]
Please try to provide sample code, my English reading ability is poor, thank you.

I understand that right?
```php
/**
 * test
 *
 * @since 1.0.0 
 *                      <- Add a blank line?
 * @param int $num num  <- Add automatically generated parameter description ?
 */
function test(int $num)
{
}
```

**Comment by shivapoudel** [comment]
@tianyiw2013 Exactly this is the scenario :)

**Comment by shivapoudel** [comment]
Any updates on this ticket, my friend :)

**Comment by tianyiw2013** [comment]
Is that so?

![vscode](https://user-images.githubusercontent.com/4644588/125010912-0ea1c400-e09a-11eb-9d15-ffd1671a4fc4.gif)

**Comment by shivapoudel** [comment]
Yes, it is like that. My suggestion, don't add up any setting, and rather than copying the param name the first demo looks great :)

**Comment by tianyiw2013** [comment]
New version 2.1.8 released. 

marketplace:
https://marketplace.visualstudio.com/items?itemName=tianyiw.php-docblocker2

CHANGELOG:
https://marketplace.visualstudio.com/items/tianyiw.php-docblocker2/changelog

**Comment by tianyiw2013** [comment]
> @since tag before @param one before with gap

It is recommended to add line feed manually

**Comment by shivapoudel** [comment]
How can I do this for functionTemplate and propertyTemplate both at a time?

Many thanks for the description support in @param. It works like charm :)

**Comment by tianyiw2013** [comment]
> How can I do this for functionTemplate and propertyTemplate both at a time?

Can you provide examples to show the results you expect?

**Comment by shivapoudel** [comment]
```
/**
 * Undocumented function (Current)
 *
 * @param [type] $string string
 * @param [type] $string2 string2
 */

/**
 * Undocumented function (I want)
 *
 * @since 1.0.0
 *
 * @param [type] $string string
 * @param [type] $string2 string2
 */
function getUser( $string, $string2 ) {
	return (string) $string + $string2;
}
```

**Comment by tianyiw2013** [comment]
see https://github.com/tianyiw2013/vscode-php-docblocker#configured-function-with-extra-content-and-placeholders

```json
// settings.json
    "php-docblocker2.functionTemplate": {
        "message": {
            "gapAfter": true
        },
        "extra": {
            "content": "@since ${###:1.0.0}",
            "gapAfter": true
        },
        "param": {},
        "return": {},
    },
```

```php
// test.php
/**
 * getUser
 *
 * @since 1.0.0
 *
 * @param mixed $string string
 * @param mixed $string2 string2
 * @return void
 */
function getUser($string, $string2)
{
}
```

**Comment by shivapoudel** [comment]
If you could add since support before param for all default template we can control behaviors easily

```
    {
        "message": {},
        "since": {}, // By default no work but if people like me want to modify then this would have been great! 
        "param": {},
        "return": {},
        "extra": {}
    }
```

So that I can simply add

```
	"php-docblocker2.extra": [
		"@since ${###:1.0.0}",
	],
```

**Comment by tianyiw2013** [comment]
OK, I see.

**Comment by shivapoudel** [comment]
Similar to how `author` is crafted. But since will be above param with gap and author is just below param.

Also please allow `"@since ${###:1.0.0}"` by default if setting is enabled in Phpdocblocker2.

Thanks in advance!

**Comment by tianyiw2013** [comment]
New version 2.1.9 released.

```json
// settings.json
"php-docblocker2.extra": [
    {
        "content": "@since ${###:1.0.0}",
        "after": "message",
        "gapAfter": true,
    },
    {
        "before": "return",
        "gapAfter": true,
    },
    {
        "content": "@see http://php.cn",
        "gapBefore": true,
        "gapAfter": true,
    },
    "hello world",
],
```

```php
// test.php
/**
 * likethis
 *
 * @since 1.0.0
 *
 * @param string $username 
 * @param string $password 
 * @param string|null $confirm_password 
 *
 * @return bool
 *
 * @see http://php.cn
 *
 * hello world
 */
function likethis(string $username, string $password, string $confirm_password = null): bool
{
}
```

**Comment by tianyiw2013** [comment]
Settings for you.

```json
// settings.json
"php-docblocker2.extra": [
    {
        "content": "@since ${###:1.0.0}",
        "after": "message",
        "gapAfter": true,
    },
],
```

**Comment by shivapoudel** [comment]
One small suggestion which I forgot to mention before:

```php
	/**
	 * Post type.
	 *
	 * @since 5.8.0
	 * <--- According to WordPress coding standard we need this gap to be removed after since, how can I?
	 * @var string
	 */
	protected $post_type;
```

**Comment by shivapoudel** [comment]
Please see this class screenshot:
![image](https://user-images.githubusercontent.com/3774827/125033028-837ef900-e0ae-11eb-93f6-d7977d2c0d09.png)

**Comment by tianyiw2013** [comment]
```json
    "php-docblocker2.extra": [
        {
            "content": "@since ${###:1.0.0}",
            "after": "message",
        },
    ],
```

**Comment by tianyiw2013** [comment]
New version 2.1.10 released. #12
